/**
 * Applies SQL migrations (generated by drizzle-kit) to the configured
 * database. Works with both postgres-js and PGlite drivers.
 *
 * CLI: `npm run db:migrate`
 * Also called from the Nitro startup plugin so deployments self-migrate.
 */
import path from 'node:path'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

function resolveMigrationsFolder(): string {
  if (process.env.MIGRATIONS_DIR) return process.env.MIGRATIONS_DIR
  // Candidates cover: plain tsx scripts, nuxt dev (bundled into .nuxt/dev),
  // and the Docker production image.
  const here = path.dirname(fileURLToPath(import.meta.url))
  const candidates = [
    path.resolve(process.cwd(), 'server/database/migrations'),
    path.resolve(here, 'migrations'),
    path.resolve(process.cwd(), 'migrations'),
  ]
  for (const c of candidates) {
    if (existsSync(path.join(c, 'meta', '_journal.json'))) return c
  }
  return candidates[0]!
}

export async function runMigrations(migrationsFolder?: string) {
  const folder = migrationsFolder || resolveMigrationsFolder()

  const url = process.env.NUXT_DATABASE_URL || process.env.DATABASE_URL || ''

  if (url.startsWith('postgres://') || url.startsWith('postgresql://')) {
    const { drizzle } = await import('drizzle-orm/postgres-js')
    const { migrate } = await import('drizzle-orm/postgres-js/migrator')
    const { default: postgres } = await import('postgres')
    const client = postgres(url, { max: 1, onnotice: () => {} })
    try {
      await migrate(drizzle(client), { migrationsFolder: folder })
    }
    finally {
      await client.end()
    }
    return
  }

  const { PGlite } = await import('@electric-sql/pglite')
  const { drizzle } = await import('drizzle-orm/pglite')
  const { migrate } = await import('drizzle-orm/pglite/migrator')
  const { mkdirSync } = await import('node:fs')
  const dataDir = url.replace(/^pglite:\/\//, '') || './.data/pglite'
  mkdirSync(dataDir, { recursive: true })
  const pglite = new PGlite(dataDir)
  try {
    await migrate(drizzle(pglite), { migrationsFolder: folder })
  }
  finally {
    await pglite.close()
  }
}

// Run directly as a CLI script
if (process.argv[1] && process.argv[1].replace(/\\/g, '/').endsWith('database/migrate.ts')) {
  runMigrations()
    .then(() => {
      console.log('✔ migrations applied')
      process.exit(0)
    })
    .catch((err) => {
      console.error('✖ migration failed', err)
      process.exit(1)
    })
}
